### ISSUE TITLE
Using the SDK with node

### ISSUE THREAD

**Issue by gautamchitnis** [uphold/uphold-sdk-javascript#20]
#### Description

I'm trying to use the SDK for building a node application.

I'm unable to find any documentation, examples or any other resources that provide info on how to use the SDK in node environment, i.e. where we use *require()* instead of *import* .

Docs over at https://uphold.github.io/uphold-sdk-javascript/sdk.html describe how to use the sdk in case of *import* only, which doesn't work on node.

I can provide more info on this issue if needed.

#### Related issues

< none >

#### Versions

Node : 10.5.0
SDK Ver: 2.3.0

**Comment by pgom** [comment]
Hey @gautamchitnis, not sure I followed your question entirely but if you don't/can't use the `import` notation, you are still able to import it using require.

**Comment by pgom** [comment]
Hey @gautamchitnis, after you initialize the `SDK` you will have to import it and use it on every file that you might need those. That will not be globally available. I'm guessing that is what you're asking.

**Comment by ricardogama** [comment]
@gautamchitnis You need to deconstruct the default export:

```js
const { default: SDK } = require('@uphold/uphold-sdk-javascript');

const sdk = new SDK({
  clientId: 'foo',
  clientSecret: 'bar'
});
```

Or access it directly:

```js
const SDK = require('@uphold/uphold-sdk-javascript');

const sdk = new SDK.default({
  clientId: 'foo',
  clientSecret: 'bar'
});
```

**Comment by gautamchitnis** [comment]
@pgom I was looking for what @ricardogama has provided here.

Thanks for the help.
